# Build master commits
trigger:
  batch: false
  branches:
    include:
      - master
      - azure*

# Enable PR triggers that target the master branch
pr:
  autoCancel: true # cancel previous builds on push
  branches:
    include:
      - master

jobs:
  - template: ./.azure/linux-stack.yml
  - template: ./.azure/windows-stack.yml

# Disable benchmarks until we can figure out why they get stuck
  # - template: ./.azure/linux-bench.yml
