resolver: nightly-2020-09-02

packages:
- .
- ./hie-compat/

extra-deps:
- haskell-lsp-0.22.0.0
- haskell-lsp-types-0.22.0.0
- lsp-test-0.11.0.6
- ghc-check-0.5.0.1
- hie-bios-0.7.1
- ghc-events-0.13.0
- ghc-trace-events-0.1.2.1
- heapsize-0.3.0
- opentelemetry-0.6.1
- opentelemetry-extra-0.6.1

# not yet in stackage
- Chart-diagrams-1.9.3
- SVGFonts-1.7.0.1
- diagrams-1.4
- diagrams-svg-1.4.3
- diagrams-contrib-1.4.4
- diagrams-core-1.4.2
- diagrams-lib-1.4.3
- diagrams-postscript-1.5
- monoid-extras-0.5.1
- svg-builder-0.1.1
- active-0.2.0.14
- dual-tree-0.2.2.1
- force-layout-0.4.0.6
- statestack-0.3
- implicit-hie-0.1.2.5
- implicit-hie-cradle-0.3.0.2

nix:
  packages: [zlib]
