resolver: nightly-2019-09-16
packages:
- .
extra-deps:
- haskell-lsp-0.19.0.0
- haskell-lsp-types-0.19.0.0
- lsp-test-0.9.0.0
- hie-bios-0.3.0
- fuzzy-0.1.0.0
- regex-base-0.94.0.0
- regex-tdfa-1.3.1.0
nix:
  packages: [zlib]
