jobs:
- job: ghcide_stack_linux
  timeoutInMinutes: 60
  pool:
    vmImage: 'ubuntu-latest'
  variables:
      STACK_ROOT: $(Pipeline.Workspace)/.stack
  steps:
  - checkout: self
  - task: Cache@2
    inputs:
      key: stack-root-cache | $(Agent.OS) | $(Build.SourcesDirectory)/stack.yaml | $(Build.SourcesDirectory)/ghcide.cabal
      path: $(STACK_ROOT)
      cacheHitVar: STACK_ROOT_CACHE_RESTORED
    displayName: "Cache stack root"
  - task: Cache@2
    inputs:
      key: stack-work-cache | $(Agent.OS) | $(Build.SourcesDirectory)/stack.yaml | $(Build.SourcesDirectory)/ghcide.cabal
      path: .stack-work
      cacheHitVar: STACK_WORK_CACHE_RESTORED
    displayName: "Cache stack work"
  - bash: |
      ./fmt.sh
    displayName: "HLint via ./fmt.sh"
  - bash: |
      sudo add-apt-repository ppa:hvr/ghc
      sudo apt-get update
      sudo apt-get install -y g++ gcc libc6-dev libffi-dev libgmp-dev make zlib1g-dev cabal-install-3.2
      if ! which stack >/dev/null 2>&1; then
         curl -sSL https://get.haskellstack.org/ | sh
      fi
      mkdir -p $STACK_ROOT
    displayName: 'Install Stack'
  - bash: stack setup
    displayName: 'stack setup'
  - bash: cabal update # some tests use Cabal cradles
    displayName: 'cabal update'
  - bash: stack build --test --no-run-tests
    displayName: 'stack build --test --no-run-tests'
