jobs:
- job: ghcide_stack_windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      stack_810:
        STACK_YAML: "stack8101.yaml"
      stack_88:
        STACK_YAML: "stack88.yaml"
      stack_86:
        STACK_YAML: "stack.yaml"
      stack_ghc_lib_88:
        STACK_YAML: "stack-ghc-lib.yaml"
  variables:
      STACK_ROOT: "C:\\sr"
  steps:
  - checkout: self
  - task: Cache@2
    inputs:
      key: stack-root-cache | $(Agent.OS) | $(Build.SourcesDirectory)/$(STACK_YAML) | $(Build.SourcesDirectory)/ghcide.cabal
      path: $(STACK_ROOT)
      cacheHitVar: STACK_ROOT_CACHE_RESTORED
    displayName: "Cache stack root"
  - task: Cache@2
    inputs:
      key: stack-work-cache | $(Agent.OS) | $(Build.SourcesDirectory)/$(STACK_YAML) | $(Build.SourcesDirectory)/ghcide.cabal
      path: .stack-work
      cacheHitVar: STACK_WORK_CACHE_RESTORED
    displayName: "Cache stack work"
  - bash: |
      ./fmt.sh
    displayName: "HLint via ./fmt.sh"
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      mkdir -p "$STACK_ROOT"
    displayName: 'Install Stack'
  - bash: stack setup --stack-yaml $STACK_YAML
    displayName: 'stack setup'
  - bash: |
      # Installing happy and alex standalone to avoid error "strip.exe: unable to rename ../*.exe; reason: File exists"
      stack install happy --stack-yaml $STACK_YAML
      stack install alex --stack-yaml $STACK_YAML
      stack install cabal-install --stack-yaml $STACK_YAML
      # GHC 8.10.1 fails with ghc segfaults, using -fexternal-interpreter seems to make it working
      # There are other transient errors like timeouts downloading from stackage so we retry 3 times
      if [ "$STACK_YAML" = "stack8101.yaml" ]; then
        stack build --only-dependencies --stack-yaml $STACK_YAML --ghc-options="-fexternal-interpreter" || stack build --only-dependencies --stack-yaml $STACK_YAML --ghc-options="-fexternal-interpreter" || stack build --only-dependencies --stack-yaml $STACK_YAML  --ghc-options="-fexternal-interpreter"
      else
        stack build --only-dependencies --stack-yaml $STACK_YAML || stack build --only-dependencies --stack-yaml $STACK_YAML || stack build --only-dependencies --stack-yaml $STACK_YAML
      fi
    displayName: 'stack build --only-dependencies'
  - bash: |
      if [ "$STACK_YAML" = "stack8101.yaml" ]; then
        stack test --no-run-tests --ghc-options="-Werror -fexternal-interpreter" --stack-yaml $STACK_YAML || stack test --no-run-tests --ghc-options="-Werror -fexternal-interpreter" --stack-yaml $STACK_YAML || stack test --no-run-tests --ghc-options="-Werror -fexternal-interpreter" --stack-yaml $STACK_YAML
      else
        stack test --no-run-tests --ghc-options=-Werror --stack-yaml $STACK_YAML
      fi
    displayName: 'stack test --ghc-options=-Werror'
    # TODO: run test suite when failing tests are fixed or marked as broken. See https://github.com/digital-asset/ghcide/issues/474
