jobs:
- job: ghcide_stack_windows
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-2019'
  variables:
      STACK_ROOT: "C:\\sr"
  steps:
  - checkout: self
  - task: Cache@2
    inputs:
      key: stack-root-cache | $(Agent.OS) | $(Build.SourcesDirectory)/stack-windows.yaml | $(Build.SourcesDirectory)/ghcide.cabal
      path: $(STACK_ROOT)
      cacheHitVar: STACK_ROOT_CACHE_RESTORED
    displayName: "Cache stack root"
  - task: Cache@2
    inputs:
      key: stack-work-cache | $(Agent.OS) | $(Build.SourcesDirectory)/stack-windows.yaml | $(Build.SourcesDirectory)/ghcide.cabal
      path: .stack-work
      cacheHitVar: STACK_WORK_CACHE_RESTORED
    displayName: "Cache stack work"
  - bash: |
      ./fmt.sh
    displayName: "HLint via ./fmt.sh"
  - bash: |
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/
      mkdir -p "$STACK_ROOT"
    displayName: 'Install Stack'
  - bash: stack setup --stack-yaml stack-windows.yaml
    displayName: 'stack setup'
  - bash: |
      # Installing happy and alex standalone to avoid error "strip.exe: unable to rename ../*.exe; reason: File exists"
      stack install happy --stack-yaml stack-windows.yaml
      stack install alex --stack-yaml stack-windows.yaml
      choco install -y cabal --version=$CABAL_VERSION
      $(cygpath $ProgramData)/chocolatey/bin/RefreshEnv.cmd
      # GHC 8.10.1 fails with ghc segfaults, using -fexternal-interpreter seems to make it working
      # There are other transient errors like timeouts downloading from stackage so we retry 3 times
        stack build --only-dependencies --stack-yaml stack-windows.yaml --ghc-options="-fexternal-interpreter" || stack build --only-dependencies --stack-yaml stack-windows.yaml --ghc-options="-fexternal-interpreter" || stack build --only-dependencies --stack-yaml stack-windows.yaml  --ghc-options="-fexternal-interpreter"
    displayName: 'stack build --only-dependencies'
  - bash: |
      stack test --ghc-options=-Werror --stack-yaml stack-windows.yaml --ta "--rerun-update" || stack test --ghc-options=-Werror --stack-yaml=stack-windows.yaml --ta "--rerun" || LSP_TEST_LOG_COLOR=0 LSP_TEST_LOG_MESSAGES=true LSP_TEST_LOG_STDERR=true stack test --ghc-options=-Werror --stack-yaml=stack-windows.yaml --ta "--rerun"
    displayName: 'stack test --ghc-options=-Werror'
