name: Testing

on: [push, pull_request]
jobs:
  test:
    timeout-minutes: 360
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.2', '8.10.1', '8.8.4', '8.8.3', '8.8.2', '8.6.5', '8.6.4']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: windows-latest
            ghc: '8.10.2' # broken due to https://gitlab.haskell.org/ghc/ghc/-/issues/18550
          - os: windows-latest
            ghc: '8.8.4' # also fails due to segfault :(
          - os: windows-latest
            ghc: '8.8.3' # fails due to segfault
          - os: windows-latest
            ghc: '8.8.2' # fails due to error with Cabal

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.3
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'

    - run: ./fmt.sh
      name: "HLint via ./fmt.sh"

    - name: Cache Cabal
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-test

    - run: cabal update

    - name: cabal configure
      run: |
        echo "tests: True" > cabal.project.local
        echo "package ghcide" >> cabal.project.local
        echo "  ghc-options: -Werror" >> cabal.project.local

    - name: Build
      shell: bash
      # Retry it three times to workaround compiler segfaults in windows
      run: cabal build || cabal build || cabal build

    - name: Test
      shell: bash
      # run the tests without parallelism to avoid running out of memory
      run: cabal test --test-options="-j1 --rerun-update" || cabal test --test-options="-j1 --rerun" || LSP_TEST_LOG_COLOR=0 LSP_TEST_LOG_MESSAGES=true LSP_TEST_LOG_STDERR=true cabal test --test-options="-j1 --rerun"
